<a href="https://colab.research.google.com/github/krajkumar6/deeplearning/blob/master/other_projects%5CMLP%20network%20to%20learn%20linear%20weights%5CMLP_for_simple_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import pandas as pd

In [0]:
# from google.colab import drive
# drive.mount('/content/gdrive')

In [0]:
cd /content/gdrive/My Drive/Colab Notebooks/Deep Learning Projects/MLP for learning weights

/content/gdrive/My Drive/Colab Notebooks/Deep Learning Projects/MLP for learning weights


# Read and Prepare the data

In [0]:
df = pd.read_csv('data.csv')
test_data = pd.read_csv('test_data.csv')

In [0]:
data_columns = ['x1','x2']

In [0]:
inputs = df[data_columns]
target = df['y']
inputs = torch.tensor(inputs.values).float()
target = torch.tensor(target.values).float()

test_data = torch.tensor(test_data.values).float()

In [0]:
print('Input Size is {}'.format(inputs.size()))
print('Target Size is {}'.format(target.size()))

print('Test Size is {}'.format(test_data.size()))


Input Size is torch.Size([100, 2])
Target Size is torch.Size([100])
Test Size is torch.Size([20, 2])


In [0]:
print(inputs[:5])
print(target[:5])

tensor([[ 3.,  5.],
        [42., 39.],
        [39., 25.],
        [21., 24.],
        [ 7., 32.]])
tensor([ 42., 402., 306., 228., 220.])


In [0]:
# #number of workers
# num_workers = 0

# #batch size
# batch_size = 20

# Define the Network Architecture

In [0]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
  
  def __init__(self):
    super(Net,self).__init__()
    
    hidden1 = 3
    hidden2 = 5 

    self.fc1 = nn.Linear(2,hidden1)
    self.fc2 = nn.Linear(hidden1,hidden2)
    self.fc3 = nn.Linear(hidden2,1)
    
     
  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
    
#instantiate the model

model = Net()
print(model)

Net(
  (fc1): Linear(in_features=2, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=5, bias=True)
  (fc3): Linear(in_features=5, out_features=1, bias=True)
)


# Specify Loss function & Optimizer

In [0]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=1e-6)

# Train the model

In [0]:
model.train()

#epochs
epochs = 2000


for x in range(epochs):
  #initialize the training loss to 0
  train_loss = 0
  #clear out gradients
  optimizer.zero_grad() 
  
  #calculate the output
  output = model(inputs)
  
  #calculate loss
  loss = criterion(output,target)
  
  #backpropagate
  loss.backward() 
  
  #update parameters
  optimizer.step()
  
  if ((x%10)==0):
    print('Training Loss after epoch {:2d} is {:2.6f}'.format(x,loss))

Training Loss after epoch  0 is 75940.937500
Training Loss after epoch 10 is 75452.031250
Training Loss after epoch 20 is 75083.031250
Training Loss after epoch 30 is 74797.062500
Training Loss after epoch 40 is 74565.687500
Training Loss after epoch 50 is 74370.039062
Training Loss after epoch 60 is 74200.390625
Training Loss after epoch 70 is 74044.273438
Training Loss after epoch 80 is 73891.898438
Training Loss after epoch 90 is 73735.851562
Training Loss after epoch 100 is 73568.281250
Training Loss after epoch 110 is 73380.132812
Training Loss after epoch 120 is 73171.781250
Training Loss after epoch 130 is 72923.945312
Training Loss after epoch 140 is 72613.601562
Training Loss after epoch 150 is 72212.085938
Training Loss after epoch 160 is 71676.210938
Training Loss after epoch 170 is 70935.335938
Training Loss after epoch 180 is 69880.617188
Training Loss after epoch 190 is 68326.046875
Training Loss after epoch 200 is 65964.929688
Training Loss after epoch 210 is 62322.05468

# Inference Section

In [0]:
#set the model in evaluation mode
model.eval()

#Test the model on unseen data

test_output = model(test_data)

In [0]:
print('Test Output Size is {}'.format(test_output.size()))

Test Output Size is torch.Size([20, 1])


In [0]:
print(test_data)

tensor([[ 3.,  5.],
        [48.,  7.],
        [46., 21.],
        [31., 50.],
        [ 2., 16.],
        [35., 24.],
        [39.,  8.],
        [23., 33.],
        [19., 35.],
        [38., 46.],
        [38., 38.],
        [39., 22.],
        [39.,  2.],
        [24., 31.],
        [16., 21.],
        [14., 37.],
        [44.,  2.],
        [42., 30.],
        [20., 20.],
        [40.,  2.]])


In [0]:
print(test_output)

tensor([[ 35.2820],
        [229.7600],
        [282.9330],
        [348.2729],
        [ 79.3581],
        [250.7019],
        [197.0070],
        [240.6697],
        [232.9380],
        [359.6095],
        [324.5086],
        [258.4336],
        [170.6814],
        [236.0212],
        [159.1313],
        [221.0796],
        [191.3150],
        [305.9147],
        [171.2505],
        [174.8081]], grad_fn=<AddmmBackward>)
